import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { DEFAULT_CONFIG } from "../extensions/config.js";
import { buildConfigEditingFields } from "../extensions/config-editing-model.js";
import { createOperationCatalog } from "../extensions/operation-catalog.js";
import type { MemoryOperationsDeps } from "../extensions/memory-operation-service.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(root, "docs", "surface-reference.md");
const docsSiteOutputPath = join(
  root,
  "docs-site",
  "src",
  "content",
  "docs",
  "reference",
  "surface-reference.md",
);
const docsSiteFrontmatter = `---\ntitle: "Generated surface reference"\n---\n\n`;

type JsonSchema = {
  type?: string;
  description?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  enum?: unknown[];
  additionalProperties?: JsonSchema | boolean;
};

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function pad(value: string, width: number): string {
  return `${value}${" ".repeat(Math.max(0, width - value.length))}`;
}

function table(headers: string[], rows: string[][]): string[] {
  const escapedRows = rows.map((row) => row.map(escapeCell));
  const widths = headers.map((header, index) =>
    Math.max(header.length, 3, ...escapedRows.map((row) => row[index]?.length ?? 0)),
  );
  return [
    `| ${headers.map((header, index) => pad(header, widths[index] ?? 3)).join(" | ")} |`,
    `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`,
    ...escapedRows.map(
      (row) => `| ${row.map((cell, index) => pad(cell, widths[index] ?? 3)).join(" | ")} |`,
    ),
  ];
}

function schemaType(schema: JsonSchema | undefined): string {
  if (!schema) return "unknown";
  if (schema.enum) return schema.enum.map(String).join(" | ");
  if (schema.type === "array") return `array<${schemaType(schema.items)}>`;
  if (schema.type === "object" && schema.additionalProperties) return "object/map";
  if (schema.type) return schema.type;
  if (schema.anyOf?.length) return schema.anyOf.map(schemaType).join(" | ");
  return "unknown";
}

function parameterRows(parameters: JsonSchema): string[][] {
  const required = new Set(parameters.required ?? []);
  return Object.entries(parameters.properties ?? {}).map(([name, schema]) => [
    `\`${name}\``,
    schemaType(schema),
    required.has(name) ? "yes" : "no",
    schema.description ?? "",
  ]);
}

function createDeps(): MemoryOperationsDeps {
  return {
    getConfig: () => DEFAULT_CONFIG,
    getProjectBankId: () => "pi-project-example",
    getClient: () => ({}) as ReturnType<MemoryOperationsDeps["getClient"]>,
  };
}

export function generateSurfaceReference(): string {
  const catalog = createOperationCatalog(createDeps());
  const configFields = buildConfigEditingFields(DEFAULT_CONFIG, "pi-project-example", {
    project: {},
    global: {},
    env: {},
  });

  const lines: string[] = [
    "<!-- This file is generated by scripts/generate-surface-reference.ts. Do not edit by hand. -->",
    "",
    "This reference is generated from the operation catalog and config editing registry.",
    "",
    "## Tools",
    "",
  ];

  for (const tool of catalog.tools) {
    lines.push(`### \`${tool.name}\``, "", tool.description ?? "", "");
    const rows = parameterRows(tool.parameters as JsonSchema);
    lines.push(...table(["Parameter", "Type", "Required", "Description"], rows), "");
  }

  lines.push("## Commands", "");
  lines.push(
    ...table(
      ["Command", "Description"],
      catalog.commands.map((command) => [`\`/${command.name}\``, command.spec.description ?? ""]),
    ),
    "",
  );

  lines.push("## Config fields", "");
  lines.push(
    ...table(
      ["Field", "Tab", "Kind", "Default", "Choices", "Advanced", "Reset key", "Description"],
      configFields.map((field) => [
        `\`${field.id}\``,
        field.tab,
        field.kind,
        field.defaultValue,
        field.choices?.join(", ") ?? "",
        field.advanced ? "yes" : "no",
        field.resetKey,
        field.description,
      ]),
    ),
    "",
  );

  return `${lines.join("\n").trimEnd()}\n`;
}

const generated = generateSurfaceReference();
const docsSiteGenerated = `${docsSiteFrontmatter}${generated}`;
if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  const docsSiteCurrent = readFileSync(docsSiteOutputPath, "utf8");
  if (current !== generated || docsSiteCurrent !== docsSiteGenerated) {
    console.error("Surface reference docs are stale. Run npm run surface-reference.");
    process.exit(1);
  }
} else {
  writeFileSync(outputPath, generated);
  writeFileSync(docsSiteOutputPath, docsSiteGenerated);
}
